version: "3"
services:
  app:
    build: .
    volumes:
      - ./app:/home/user/app
      - ./packages.txt:/home/user/app/packages.txt
      # - ./packages-dev.txt:/home/user/app/packages-dev.txt
    tty: True
    container_name: node22.4-dev-container
    #ports:
    #  - "8888:8888"
    network_mode: bridge
    stop_signal: SIGKILL
