version: "3"
services:
  app:
    build: .
    volumes:
      - ./app:/home/user/app
    tty: True
    container_name: node22.4-dev-container
    #ports:
    #  - "8888:8888"
    network_mode: bridge
    stop_signal: SIGKILL
